---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-demo-service
  labels:
    app: go-demo-service
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - go-demo-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: go-demo-service-restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-demo-service
subjects:
- kind: ServiceAccount
  name: go-demo-service
